# Site settings
title: Kaylee George
description: personal website
url: "https://kayleegeorge.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Jekyll configuration for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight'